設定画面と退会機能の実装
team-musashi/stamp-rally pull request #28
Opened 2022-11-13 06:06 UTC by kuwabara-hirokazu

# 関連する Issue

- #24 

# やったこと

- 設定画面の作成
-  ホーム画面から設定画面に退会機能を移行
- ルーター設定

# やらないこと

- 設定画面のレイアウト

# スクリーンショット

https://user-images.githubusercontent.com/62511320/201508304-2aefa637-1906-4362-92a8-8a6857a64a32.mov

# その他

- レビュワーへの参考情報（実装上の懸念点や注意点、追加したパッケージなどあれば記載）

2022-11-15 14:13 UTC, kuwabara-hirokazu commented on lib/config/router.dart
> +)
単体で置きましたが、HomeRouteのroutes[]に追加していく想定でしたか？

2022-11-15 22:50 UTC, susatthi commented on lib/config/router.dart
> +)
home配下のroute[]配下に移動願います！その場合、/settingではなくsettingになるのでご注意ください！

2022-11-16 10:48 UTC, kuwabara-hirokazu commented on lib/config/router.dart
> +)
修正しました🙌
[🚀 feat: SettingRouteをHomeRouteの中に入れる](https://github.com/team-musashi/stamp-rally/pull/28/commits/625bf69bd822c5bf3924f028061e099d27a00251)

2022-11-16 11:08 UTC, susatthi requested changes
すみません、追加コメントしました！

2022-11-16 11:08 UTC, susatthi commented on lib/presentation/page/setting/setting_page.dart
> +        leading: IconButton(
settingをhome配下にすれば、これ不要になりませんか？？

2022-11-16 11:21 UTC, kuwabara-hirokazu commented on lib/presentation/page/setting/setting_page.dart
> +        leading: IconButton(
画面遷移すると自動で設定されるんですね知らなかったです😮
ありがとうございます！
[🚀 feat: 戻るアイコンは自動的に設置されるため、アイコン設定を削除](https://github.com/team-musashi/stamp-rally/pull/28/commits/3a788d8ce7d8de0932cb8dcf12fb189968d84c60)

2022-11-16 11:23 UTC, susatthi approved these changes
![LGTM](https://image.lgtmoon.dev/187949)

2022-11-16 11:25 UTC, susatthi commented
マージおなしゃすー

2022-11-16 11:26 UTC, merged